### ISSUE TITLE
Brizi - Senior Full Stack Developer - Toronto

### ISSUE THREAD

**Issue by samidalati** [TechnologyMasters/jobs#15] opened 2017-08-29 17:47 UTC
### Salary Expectation
- $70K – $120K 
- 0.0% – 1.0%
- Full Time

### Location
- Toronto, Ontario

## What You'll Do
- Building front-end, back-end API’s and databases using the MEAN Stack (MongoDB, Express.js, Angular, and Node.js) 
- Monitor, identify and relieve bottlenecks and restraints on production systems through development and system tuning. 
- Ensure the web applications, production software, and server architecture is scalable, stable and secure. 
- Use analytical thinking skills to optimize performance of very complex apps 
- Test, troubleshoot, document current and future development. 
- Ensure a cohesive experience across different browsers and devices 
- Other projects as required

## What You Need to Be Successful 
- Experience in architecture design and developing large-scale, event-driven, data-oriented systems 
- Extensive skills with Node.js, JavaScript, html, CSS, and other programming languages. 
- Strong leadership, problem solving, and communication skills, workign with Agile/DevOps practices 
- Knowledge with MongoDB/Mongoose databases and Redis. 
- Knowledge in Amazon cloud services: EC2, S3, Lambda, DynamoDB 
- Knowledge in Facebook, Twitter API, and Google Analytics 
- Proficiency with Linux operating systems. 
- Self-motivated, detail-oriented and organized. 
- A team player, able to effectively collaborate and build relationships over any medium of communication

### Must Have
- 3+ years working as a NodeJS developer
- 2+ years working with Mongodb; Express, Angular

### Nice to Have
- Python
- AI
- C++
- Eye for design

## About Our company
Brizi is looking for outstanding individuals to join our team. Are you a sports fan or have friends that go nuts over sports? We are building the future of fan experiences! Here's a quickie on how:

- There's a lack of authenticity in brand marketing in this day and age, especially when it comes to the all-too-familiar billboards or giveaways in sports stadiums. These sponsors want real, measurable ROI for their extensive dollars spent in sponsorship. 
- We believe that the value of sponsoring experiences lies in the unforgettable moments created, the emotional energy of the arena, that electricity in the air no one can replicate. 
- That's why Brizi provides fans the thrill of taking control over a robotic camera in-stadium that SWIVELS to find you, instantly deliver the moments you captured to your phone. Our proprietary technology is licensed to Sports Properties that sell to brands who want to be associated with experiences. 
- We have customers across the NBA, NFL, MLS, Grand Slam Tennis, and the list is growing fast. To date, Brizi has captivated users from 95 different countries, across over 4,200 hours of usage time.

We believe in people who have demonstrated potential, can ask smart questions, and possess the ability to figure things out along the way! At Brizi, you have full ownership of your work and autonomy in every aspect. WARNING: this is not a 9 to 5. This is an environment where the expectation is to exceed expectations. We call each other out on BS and we’re there for each other through hard times in our personal lives. This blurring of the line between professional and personal may not be for everyone, but it’s what makes the Brizi family special.

## How to apply

Please apply at https://angel.co/brizi/jobs/244965-full-stack-web-developer 

---
## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by ahmadnassri** [comment] 2017-08-30 01:38
duplicate of #16

**Closed by ahmadnassri** 2017-08-30 01:38 UTC
Labels: full time, salary
